# Generated by Django 5.1.1 on 2024-09-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0002_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_id',
            field=models.IntegerField(choices=[(1, 'Ali Osman'), (2, 'Mohamed Abdo'), (3, 'Mohamed Yasser')], default=1),
        ),
    ]
