# Generated by Django 5.1.1 on 2024-09-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api', '0004_alter_transaction_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user_id',
            field=models.IntegerField(choices=[(1, '1- Ali Osman'), (2, '2- Mohamed Abdo'), (3, '3- Mohamed Yasser')], default=1),
        ),
    ]
